# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aae4c04b1d1cb34ef64ce404a07a4206e99643b1c63460c598cb75c4c393a41d275f2f32c25afa0921d42bd11a386a437f1c8b1117e491d59a8456d86cd32ded

test:
  secret_key_base: a10e4b630ccaad9df14437ff16cc9178f9ed9710feac892c6e7ad6fd72946cf9ad0d217c16bd99ca9f6fcff199b98c2bd46ec2663e60c49e1cc93c20f6aee342

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
